version: "3"
services:
  web:
    build: .
    container_name: symfony_web
    volumes:
      - ./src:/var/www/html/src
      - ./virtualhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "8080:80"
