version: "3"
services:
  web:
    build: .
    container_name: symfony_web
    volumes:
      - ./src:/var/www/html/src
      - ./virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    restart: always
    ports:
      - "8080:80"
